import { NextResponse } from 'next/server';
import jwt from 'jsonwebtoken';
import { createTransaction } from '@/lib/repository/transaction.repository';
import {
  createStakingEvent,
  deleteStakingPosition,
  findStakingPositionById,
  updateStakingPosition,
} from '@/lib/repository/staking.repository';

function getUserIdFromRequest(request) {
  const authHeader = request.headers.get('authorization');
  if (!authHeader) return null;

  const token = authHeader.split(' ')[1];
  if (!token) return null;

  const decoded = jwt.verify(token, process.env.JWT_SECRET);
  return decoded.userId;
}

export async function POST(request, { params }) {
  try {
    const userId = getUserIdFromRequest(request);
    if (!userId) {
      return NextResponse.json({ error: 'No autorizado' }, { status: 401 });
    }

    const { id } = params;
    const positionId = parseInt(id, 10);
    const body = await request.json();
    const amountToUnstake = Number(body.amountToUnstake);

    if (!Number.isFinite(positionId) || positionId <= 0) {
      return NextResponse.json({ error: 'Posición inválida' }, { status: 400 });
    }

    if (!Number.isFinite(amountToUnstake) || amountToUnstake <= 0) {
      return NextResponse.json(
        { error: 'La cantidad a retirar debe ser mayor que 0' },
        { status: 400 }
      );
    }

    const position = await findStakingPositionById(positionId, userId);
    if (!position) {
      return NextResponse.json({ error: 'Posición no encontrada' }, { status: 404 });
    }

    const now = new Date();
    const startDate = new Date(position.startDate);
    const stakedDays = Math.max(
      1,
      Math.floor((now.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24))
    );
    const principalWithdrawn = Number(Math.min(amountToUnstake, position.amountStaked).toFixed(8));
    const rewardAmount = Number(Math.max(amountToUnstake - principalWithdrawn, 0).toFixed(8));

    const realizedApy = rewardAmount > 0
      ? (rewardAmount / principalWithdrawn) * (365 / stakedDays) * 100
      : 0;

    const remainingAmount = Number((position.amountStaked - principalWithdrawn).toFixed(8));

    if (rewardAmount > 0) {
      await createTransaction({
        userId,
        assetTicker: position.assetTicker,
        type: 'BUY',
        quantity: rewardAmount,
        pricePerUnit: 0,
        fees: 0,
        date: now.toISOString(),
        notes: 'Reward generated by staking withdrawal',
      });
    }

    await createStakingEvent({
      userId,
      stakingPositionId: position.id,
      assetTicker: position.assetTicker,
      eventType: 'UNSTAKE',
      principalAmount: principalWithdrawn,
      rewardAmount,
      realizedApy,
      stakedDays,
      createdAt: now,
    });

    if (remainingAmount <= 0) {
      await deleteStakingPosition(position.id);
    } else {
      await updateStakingPosition(position.id, {
        amountStaked: remainingAmount,
      });
    }

    return NextResponse.json({
      message: 'Retirada de staking procesada',
      positionId: position.id,
      assetTicker: position.assetTicker,
      unstakedAmount: principalWithdrawn,
      rewardAmount,
      realizedApy,
      stakedDays,
      remainingAmount,
    });
  } catch (error) {
    console.error('Error al retirar staking:', error);
    return NextResponse.json(
      { error: 'Error al procesar la retirada de staking' },
      { status: 500 }
    );
  }
}
